name: Main CI 🔮

concurrency:
  group: ${{ github.ref }}-main-ci
  cancel-in-progress: false

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  pre-checks:
    uses: ./.github/workflows/_01_pre_checks.yml
    secrets: inherit
  checks:
    needs: [pre-checks]
    uses: ./.github/workflows/_02_checks.yml
    secrets: inherit
  docker:
    needs: [pre-checks, checks]
    uses: ./.github/workflows/_docker_build.yml
    with:
      image_name: ${{ github.repository }}/info-bot
      tags: |
        type=raw,value=latest
        type=raw,value=main-${{ github.sha }}
